import random
from discord.ext import commands
from discord import app_commands

class Joke(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.jokes = [
            "I told my wife she was drawing her eyebrows too high. She looked surprised.",
            "Why don’t scientists trust atoms? Because they make up everything.",
            "Parallel lines have so much in common… it’s a shame they’ll never meet.",
            "I have a joke about construction, but I’m still working on it.",
            "Why did the scarecrow win an award? Because he was outstanding in his field.",
            "I would tell you a dark joke… but the shadows object.",
            "Why don’t graveyards ever get overcrowded? People are dying to get in.",
            "I’m reading a book about anti-gravity. It’s impossible to put down.",
            "Why did the chicken cross the playground? To get to the other slide.",
            "I used to play piano by ear… now I use my hands.",
            "Why don’t scientists trust atoms? Because they make up everything! 😂",
            "I told my computer I needed a break, and now it won’t stop sending me KitKat ads 🍫",
            "Why did the scarecrow win an award? Because he was outstanding in his field! 🌾",
            "Parallel lines have so much in common… it’s a shame they’ll never meet. 😭",
            "I would tell you a construction pun… but I’m still working on it! 🏗️",
            "I asked the gym instructor if he could teach me to do the splits… He said, 'How flexible are you?' I said, 'I can’t make it on Tuesdays.' 😅",
            "Why did the coffee file a police report? It got mugged ☕",
            "I’m reading a book about anti-gravity… it’s impossible to put down! 📚",
            "Why did the chicken go to the seance? To talk to the other side 🐔",
            "I told my wife she should embrace her mistakes… She hugged me. 😏",
             "Why don't scientists trust atoms? They make up everything! ⚛️😂",
"I told my computer I needed a break… it said 'No problem, I'll go to sleep 😴💻'",
"Parallel lines have so much in common… shame they’ll never meet. ➖➖💔",
"Why did the scarecrow win an award? Because he was outstanding in his field! 🌾🏆",
"Why do programmers prefer dark mode? Because light attracts bugs! 💡🐛",
"Why did the developer go broke? He used up all his cache 💸🖥️",
"Why did the coffee file a police report? It got mugged ☕🚨",
"Why do cows have hooves instead of feet? Because they lactose 🐄🥛",
"Why did the cookie go to the doctor? Because it felt crummy 🍪😷",
"Why did the computer go to therapy? It had too many bytes of emotional baggage 💻💔",
"Why did the JavaScript developer leave? She didn’t get closure 🌐💔",
"Why was the math book sad? It had too many problems 📚😢",
"Why did the tomato turn red? Because it saw the salad dressing 🍅👀🥗",
"I’m on a whiskey diet. I’ve lost three days already 🥃🤣",
"Did you hear about the claustrophobic astronaut? He needed a little space 🚀😅",
"Why did the skeleton not fight? He didn’t have the guts 💀😆",
"Why was the computer cold? It left its Windows open ❄️🖥️",
"Why did the Wi-Fi break up with the laptop? Too many dropped connections 📶💔",
"Why did the developer cross the road? To get to the other IDE 🛣️💻",
"Why do programmers always mix up Halloween and Christmas? Oct 31 == Dec 25 🎃🎄🤯",
"Why did the database administrator leave his wife? She had one-to-many relationships 🗃️💔",
"Why was the cell phone wearing glasses? It lost its contacts 📱🤓",
"Why do programmers love nature? No bugs, only features 🌳🐞😂",
"Why did the function go to therapy? It had unresolved parameters 🛠️🌀",
"Why did the computer fail its driving test? It couldn’t handle the cache 🖥️🚗💥",
"Why did the web developer leave the party? Too many divs 🕺💻",
"Why did the Python programmer get rejected? Indentation error in love life 🐍💔",
"Why did the coder bring string to the bar? To tie up loose ends 🍷🧵",
"Why did the hacker stay calm? He had good control keys ⌨️😎",
"Why did the programmer quit his job? He didn’t get arrays 💻📉",
"Why did the laptop go to the dentist? It had Bluetooth 😬💻",
"Why was the computer stressed out? Too many bytes to handle 😵💾",
"Why did the cookie cry? Its mom was a wafer too long 🍪😭",
"Why don’t graveyards ever get overcrowded? People are dying to get in ⚰️😂",
"Why did the coder feel cold? He left his Windows open ❄️🖥️",
"Why did the developer go broke? He had too many exceptions 💸💥",
"Why did the function refuse to work? It had commitment issues 💔🖥️",
"Why did the hacker break up with his girlfriend? She exposed his vulnerabilities 💻💔",
"Why do programmers hate summer? Too many breaks 🌞🛠️",
"Why did the programmer cross the road? Forgot the semicolon 🛣️🤯",
"Why do Java developers wear glasses? Because they don’t C# 🤓💻",
"Why did the computer go on a diet? Too many bytes 🍎💾",
"Why did the server break up with the client? Too many requests 🔁💔",
"Why did the web designer storm out? Bad layout 😡🖥️",
"Why did the Python go to school? To improve its class 🐍📚",
"Why did the computer get glasses? To improve its web sight 👓💻",
"Why did the coder refuse to argue? Null pointer exception 🧠❌",
"Why did the laptop sit near the window? It wanted more cache 🖥️🌤️",
"Why did the programmer bring a ladder? To reach high-level functions 🪜💻",
"Why did the software developer break up? Too many unresolved dependencies 💔🖥️",
"Why did the JavaScript file feel depressed? Didn’t know its scope 😞🌐",
"Why did the hacker go broke? Too many phishing attempts 🐟💻",
"Why did the programmer stay calm during the fire? He handled exceptions 🔥🖥️",
"Why did the coder go to therapy? Too many unresolved issues 🛋️💻",
"Why did the computer blush? It saw the user’s cache 💾😳",
"Why do programmers hate nature? Too many bugs 🐛🌿",
"Why did the keyboard break up with the computer? Too many keystrokes ⌨️💔",
"Why did the laptop go to the doctor? It had a virus 🖥️🦠",
"Why did the Python program get glasses? To improve its syntax 👓🐍",
"Why did the coder go broke? His cache ran out 💸💻",
"Why did the web developer refuse to fight? He didn’t want to lose his divs 🕺💻",
"Why was the computer tired? Too many tabs open 💤🖥️",
"Why did the programmer hate the ocean? Too many waves 🌊💻",
"Why did the hacker cry? He lost his cookies 🍪😭",
"Why did the coder stay home? Too many bugs outside 🐛🏠",
"Why did the computer go on vacation? Too many processes 🖥️✈️",
"Why did the JavaScript break up? Not enough closure 🌐💔",
"Why did the web page go to therapy? Too many 404 errors 🖥️😢",
"Why did the coder bring a broom? To sweep the bugs away 🧹💻",
"Why did the function fail math class? Too many arguments 📝🌀",
"Why did the developer bring a pillow? To catch some Zzz in the loop 💤💻",
"Why did the hacker go broke? Too many phishing scams 🐟💰",
"Why did the computer sit in the sun? It needed a bit of warmth ☀️💻",
"Why did the variable feel lonely? It was uninitialized 😔📊",
"Why did the programmer buy a car? To drive while debugging 🚗💻",
"Why did the computer get glasses? To improve its web sight 👓🖥️",
"Why did the coder go broke? His cache ran out 💸🖥️",
"Why did the programmer get stuck in the shower? The soap was object-oriented 🧼🛁",
"Why did the cell phone go to school? It wanted to improve its reception 📱🎓",
"Why did the coder refuse to argue? Null pointer exception 🧠❌",
"Why did the developer go broke? Too many exceptions 💸💥",
"Why did the function refuse to work? Commitment issues 💔🖥️",
"Why did the hacker break up? Vulnerabilities exposed 💻💔",
"Why did the programmer stay calm? He handled exceptions 😎💻",
"Why did the laptop sit near the window? Wanted more cache 🖥️🌤️",
"Why did the server break up? Too many requests 🔁💔",
"Why did the programmer hate summer? Too many breaks 🌞💻",
"Why did the computer blush? Saw the user’s cache 💾😳",
"Why did the web page go to therapy? Too many 404 errors 🖥️😢",
"Why did the Python program go to school? To improve its class 🐍📚",
"Why did the coder bring a ladder? Reach high-level functions 🪜💻",
"Why did the developer break up? Unresolved dependencies 💔🖥️",
"Why did the web designer storm out? Bad layout 😡🖥️",
"Why did the programmer cross the road? Forgot the semicolon 🛣️🤯",
"Why do Java developers wear glasses? They don’t C# 🤓💻",
"Why did the cookie cry? Its mom was a wafer too long 🍪😭",
"Why don’t graveyards get crowded? People dying to get in ⚰️😂",
"Why did the skeleton not fight? Didn’t have the guts 💀😆",
"Why did the computer fail its driving test? Couldn’t handle the cache 🖥️🚗",
"Why did the laptop go to the dentist? Bluetooth 😬💻"
        ]

    @commands.command()
    async def joke(self, ctx):
        joke_line = random.choice(self.jokes)
        await ctx.send(joke_line)

    @app_commands.command(name="joke", description="Get a random joke")
    async def joke_slash(self, interaction):
        joke_line = random.choice(self.jokes)
        await interaction.response.send_message(joke_line)

async def setup(bot):
    await bot.add_cog(Joke(bot))
