import discord
from discord.ext import commands
from discord import app_commands
import random

class Roast(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.roasts = [
            "Hey {user}, if I wanted to kill myself I'd climb your ego and jump to your IQ.",
            "{user}, you're as useless as the 'ueue' in 'queue'.",
            "{user}, I'd agree with you, but then we’d both be wrong.",
            "You're like a cloud. When you disappear, it’s a beautiful day, {user}.",
            "You bring everyone so much joy… when you leave the room, {user}.",
          "Hey {user}, if I wanted to kill myself I'd climb your ego and jump to your IQ.",
            "{user}, you're as useless as the 'ueue' in 'queue'.",
            "{user}, I'd agree with you, but then we’d both be wrong.",
            "You're like a cloud. When you disappear, it’s a beautiful day, {user}.",
            "{user}, your secrets are safe with me. I never even listened.",
            "{user}, you're like a software update… nobody asked for you.",
            "{user}, your brain is like a browser with 100 tabs open.",
            "{user}, if ignorance is bliss, you must be the happiest person alive.",
            "{user}, your life is like a pop-up nobody clicked: irritating.",
            "{user}, you're proof that even evolution takes coffee breaks.",
          "Hey {user}, if I wanted to kill myself I'd climb your ego and jump to your IQ.",
            "{user}, you're as useless as the 'ueue' in 'queue'.",
            "{user}, I'd agree with you, but then we’d both be wrong.",
            "{user}, you have something on your chin… no, the third one down.",
            "You're like a cloud. When you disappear, it’s a beautiful day, {user}.",
            "You bring everyone so much joy… when you leave the room, {user}.",
                 "{user}, you bring everyone so much joy… when you leave the room.",
    "{user}, you’re proof that even evolution takes coffee breaks.",
    "If ignorance is bliss, {user}, you must be the happiest person alive.",
    "{user}, your secrets are safe with me. I never even listened.",
    "{user}, you have something on your face… oh wait, that’s just your personality.",
    "{user}, you’re like a cloud. When you disappear, it’s a beautiful day.",
    "{user}, your family tree must be a cactus, because everyone on it is a prick.",
    "{user}, if laughter is the best medicine, your face must be terminal.",
    "{user}, you’re like Windows 95: outdated, slow, and full of errors.",
    "{user}, your logic is like a broken compass: completely lost.",
    "{user}, your brain has the processing speed of a snail in syrup.",
    "{user}, your confidence is like a balloon with a slow leak: sad and deflated.",
    "{user}, your humor is like decaf coffee: all hype, no punch.",
    "{user}, you sparkle… like a dull knife.",
    "{user}, your aura is like low battery mode: weak and fading.",
    "{user}, your ideas are like expired coupons: useless and forgotten.",
    "{user}, your effort is like a phone with no signal.",
    "{user}, your timing is like a paused video: always off.",
    "{user}, you’re like a software update: unnecessary and annoying.",
    "{user}, your existence is like a loading screen: endlessly frustrating.",
    "{user}, your charm is like a wet sponge: messy and unhelpful.",
    "{user}, you shine like a candle in a hurricane: ineffective.",
    "{user}, your style is like socks over sandals: tragic and confusing.",
    "{user}, your jokes are like expired milk: sour and unwelcome.",
    "{user}, your personality is like soggy toast: limp and disappointing.",
    "{user}, your presence is like a pop-up nobody clicked.",
    "{user}, your intelligence is like a dead battery: useless until recharged.",
    "{user}, your memory is like a browser with 100 tabs open: overwhelmed and useless.",
    "{user}, your aura is like a flickering fluorescent bulb: annoying and unstable.",
    "{user}, your life is like decaf tea: bland, weak, and disappointing.",
    "{user}, your confidence is like expired soda: flat and disappointing.",
    "{user}, your words are like a broken microphone: nobody hears them.",
    "{user}, you sparkle like a chipped gemstone.",
    "{user}, your logic is like a tangled headphone cord: impossible to follow.",
    "{user}, you move like a buffering video: slow and irritating.",
    "{user}, your brain is like a frozen screen: completely stuck.",
    "{user}, your style is like a traffic cone at a wedding: awkward.",
    "{user}, your humor is like a pencil without lead: pointless.",
    "{user}, your aura is like a broken streetlamp: dim and ineffective.",
    "{user}, your thinking is like a frozen screen: completely stuck.",
    "{user}, your presence is like white noise: forgettable.",
    "{user}, your life is like a software bug: nobody knows why it exists.",
    "{user}, your impact is like a paperclip in a hurricane: irrelevant.",
    "{user}, you shine like a broken streetlamp: barely noticeable and annoying.",
    "{user}, your intelligence is like a Wi-Fi signal in a cave: non-existent.",
    "{user}, your jokes are like a silent movie: nobody laughs.",
    "{user}, your energy is like a drained AA battery.",
    "{user}, your brain waves are on airplane mode.",
    "{user}, your confidence is like a punctured balloon: sad and deflated.",
    "{user}, your words are like glare on a screen: hard to focus on.",
    "{user}, your logic is like a GPS with no satellite: hopelessly lost."
    "{user}, you bring everyone so much joy… when you leave the room.",
"{user}, you’re proof that even evolution takes coffee breaks.",
"If ignorance is bliss, {user}, you must be the happiest person alive.",
"{user}, your secrets are safe with me. I never even listened.",
"{user}, you have something on your face… oh wait, that’s just your personality.",
"{user}, you’re like a cloud. When you disappear, it’s a beautiful day.",
"{user}, your family tree must be a cactus, because everyone on it is a prick.",
"If laughter is the best medicine, {user}, your face must be terminal.",
"{user}, you’re like Windows 95: outdated, slow, and full of errors.",
"{user}, your logic is like a broken compass: completely lost.",
"{user}, your brain has the processing speed of a snail in syrup.",
"{user}, your confidence is like a balloon with a slow leak: sad and deflated.",
"{user}, your humor is like decaf coffee: all hype, no punch.",
"{user}, you sparkle… like a dull knife.",
"{user}, your aura is like low battery mode: weak and fading.",
"{user}, your ideas are like expired coupons: useless and forgotten.",
"{user}, your effort is like a phone with no signal.",
"{user}, your timing is like a paused video: always off.",
"{user}, you’re like a software update: unnecessary and annoying.",
"{user}, your existence is like a loading screen: endlessly frustrating.",
"{user}, your charm is like a wet sponge: messy and unhelpful.",
"{user}, you shine like a candle in a hurricane: ineffective.",
"{user}, your style is like socks over sandals: tragic and confusing.",
"{user}, your jokes are like expired milk: sour and unwelcome.",
"{user}, your personality is like soggy toast: limp and disappointing.",
"{user}, your presence is like a pop-up nobody clicked.",
"{user}, your intelligence is like a dead battery: useless until recharged.",
"{user}, your memory is like a browser with 100 tabs open: overwhelmed and useless.",
"{user}, your aura is like a flickering fluorescent bulb: annoying and unstable.",
"{user}, your life is like decaf tea: bland, weak, and disappointing.",
"{user}, your confidence is like expired soda: flat and disappointing.",
"{user}, your words are like a broken microphone: nobody hears them.",
"{user}, you sparkle like a chipped gemstone.",
"{user}, your logic is like a tangled headphone cord: impossible to follow.",
"{user}, you move like a buffering video: slow and irritating.",
"{user}, your brain is like a frozen screen: completely stuck.",
"{user}, your style is like a traffic cone at a wedding: awkward.",
"{user}, your humor is like a pencil without lead: pointless.",
"{user}, your aura is like a broken streetlamp: dim and ineffective.",
"{user}, your thinking is like a frozen screen: completely stuck.",
"{user}, your presence is like white noise: forgettable.",
"{user}, your life is like a software bug: nobody knows why it exists.",
"{user}, your impact is like a paperclip in a hurricane: irrelevant.",
"{user}, you shine like a broken streetlamp: barely noticeable and annoying.",
"{user}, your intelligence is like a Wi-Fi signal in a cave: non-existent.",
"{user}, your jokes are like a silent movie: nobody laughs.",
"{user}, your energy is like a drained AA battery.",
"{user}, your brain waves are on airplane mode.",
"{user}, your confidence is like a punctured balloon: sad and deflated.",
"{user}, your words are like glare on a screen: hard to focus on.",
"{user}, your logic is like a GPS with no satellite: hopelessly lost."
        ]

    @app_commands.command(name="roast", description="Roast a user brutally 😈")
    @app_commands.describe(user="User to roast")
    async def roast_slash(self, interaction: discord.Interaction, user: discord.Member):
        """Slash command to roast a user"""
        if user.id == interaction.user.id:
            await interaction.response.send_message(f"Trying to roast yourself, {user.mention}? 😂 You’re doing fine!")
            return
        roast_line = random.choice(self.roasts).replace("{user}", user.mention)
        await interaction.response.send_message(roast_line)

async def setup(bot):
    await bot.add_cog(Roast(bot))
